[project]
name = "clauseguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "waniya meerab", email = "waniyameerab2005@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
clauseguard = "clauseguard:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
